name: "Build pyinstaller executable"
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-13']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - run: pip install -r Requirements.txt pyinstaller
    - run: pyinstaller game.py
    # Optionally verify that it works (provided that it does not need user interaction)
    
    - if: runner.os == 'Windows'
      - uses: actions/upload-artifact@v4
      with:
        name: Sillygame-Windows
        path: dist/*
    - if: runner.os == 'macOS'
      uses: actions/upload-artifact@v4
      with:
        name: Sillygame-Macos
        path: dist/*
    - if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: Sillygame-Linux
        path: dist/*
